// https://www.codewars.com/kata/interleaving-arrays

/*
Description:

Create a function named interleave, that accepts an arbitrary number of array arguments and returns a single array.
The function should always return an array and the returned array should be
generated by alternately appending elements from the passed in arrays.
If one list is shorter than the others, the result should be null padded.
No modifications should be made to the passed in arguments.

Example:

interleave([1, 2, 3], ['c', 'd', 'e']) // should return [1, 'c', 2, 'd', 3, 'e']
interleave([1, 2, 3], [4, 5]) // should return [1,4,2,5,3,null]
interleave([1, 2, 3], [4, 5, 6], [7, 8, 9]) // should return [1, 4, 7, 2, 5, 8, 3, 6, 9]
interleave([]) // should return []
*/

function interleave() {
  var arrs = Array.prototype.slice.call(arguments);
  var lens = arrs.map(function(a){
    return a ? a.length : 0;
  });

  var max = Math.max( ...lens );

  var result = [];

  for( var i = 0; i < max; i++ ) {
    for( var j = 0; j < arrs.length; j++ ) {
      result.push( arrs[j][i] || null );
    }
  }

  return result;
};

module.exports = interleave;

// best practice
function interleave() {
  var outRay = [];
  arguments = Array.prototype.slice.call(arguments);

  for (var x=0; arguments[0] && x < arguments[0].length; x++ ) {
    arguments.forEach( function(y) {
      outRay.push( y[x] );
    });
  }

  return outRay;
}
